FROM gcc:latest

# Set the working directory for C code
WORKDIR /app

# Copy C code into the Docker image
COPY server/main.c .

# Compile C code with pthread support
RUN gcc -o c_server main.c -lpthread

# Make the C server executable
RUN chmod +x c_server

CMD ["/app/c_server"]
